#!/bin/bash

# read file name
read -p "Enter file name: " file

# write "#!/bin/bash" into file
echo "#!/bin/bash" > $file

# write code line into file
read -p "Write code line: " code_line
echo "$code_line" >> $file

# add executory permissin to file
chmod u+x $file

# git actions
read -p "Git message: " message
git add .
git commit -m "$message"
git push

